-- =====================================================================
-- 02 · SEED DEL CATÁLOGO
-- Generado desde el catálogo del dashboard (PDF Paquetes de Experiencias).
-- 32 paquetes + 1 de servicios individuales, con itinerarios y comedores.
-- =====================================================================

-- COMUNIDADES
insert into comunidades (id, nombre, color, orden) values
  ('cuajimoloyas', 'Cuajimoloyas', '#1F7D5E', 0),
  ('benito_juarez', 'Benito Juárez', '#2563EB', 1),
  ('llano_grande', 'Llano Grande', '#84CC16', 2),
  ('la_neveria', 'La Nevería', '#0891B2', 3),
  ('latuvi', 'Latuvi', '#B45309', 4),
  ('lachatao', 'Lachatao', '#7C3AED', 5),
  ('amatlan', 'Amatlán', '#DC2626', 6),
  ('capulalpam', 'Capulálpam', '#DB2777', 7),
  ('san_miguel_del_valle', 'San Miguel del Valle', '#D97706', 8),
  ('teotitlan_del_valle', 'Teotitlán del Valle', '#14B8A6', 9)
on conflict (id) do update set nombre=excluded.nombre, color=excluded.color;

-- GUÍAS
insert into guias (nombre, bilingue, idiomas) values
  ('Carlos Ruiz', true, 'Español / Inglés'),
  ('Ana Pérez', false, null),
  ('Miguel Cruz', false, null),
  ('Lucía Nolasco', true, 'Español / Inglés'),
  ('Diego Ávila', false, null),
  ('Rosa Méndez', false, null),
  ('Pablo Jiménez', true, 'Español / Inglés')
on conflict (nombre) do nothing;

-- PLANTILLA DE CHECKLIST
insert into checklist_plantilla (ambito, item, orden) values
  ('general', 'Transporte confirmado', 0),
  ('general', 'Anfitrión bilingüe asignado', 1),
  ('general', 'Seguros vigentes', 2),
  ('general', 'Kits de emergencia', 3),
  ('general', 'Lista de pasajeros enviada', 4),
  ('comunidad', 'Guía de la comunidad confirmado', 0),
  ('comunidad', 'Hospedaje confirmado', 1),
  ('comunidad', 'Comedores confirmados', 2),
  ('comunidad', 'Permisos comunitarios', 3)
on conflict (ambito, item) do nothing;

-- PAQUETES
insert into paquetes (id, nombre, duracion, descripcion, precio, fecha_inicio, fecha_fin, status, anfitrion_idiomas, transporte_tipo) values
  ('p01', 'Cañón del Coyote', '1 día', 'Caminata por bosques de pino-encino explorando el Ojito de Agua y el Cañón del Coyote, con gastronomía local y actividades recreativas en la comunidad.', 900, '2026-07-03', '2026-07-03', 'Confirmado', 'Español / Inglés', 'Van'),
  ('p02', 'Mirador El Calvario', '1 día', 'Senderismo entre bosques y miradores panorámicos, con gastronomía local y actividades recreativas en la comunidad.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p03', 'Mi Experiencia Rural', '1 día', 'Integración a la vida comunitaria con actividades de campo, cocina tradicional con productos orgánicos y senderismo hacia miradores.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p04', 'Los Molinos', '1 día', 'Recorrido por senderos naturales hasta ríos y espacios recreativos, con paisajes de montaña y gastronomía local.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p05', 'Las Minas', '1 día', 'Caminata guiada por senderos, miradores y paisajes naturales hasta el río, con comida en la comunidad.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p06', 'Cueva Iglesia', '1 día', 'Caminata de mayor intensidad entre paisajes de montaña, miradores, formaciones rocosas y senderos históricos.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p07', 'Los Colores del Maíz', '1 día', 'Valor cultural del maíz a través de recorridos en campos de cultivo, talleres de cocina tradicional y convivencia con la comunidad.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p08', 'Aves del Bosque', '1 día', 'Tour de observación de aves: senderismo y avistamiento en hábitat natural, con gastronomía local.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p09', 'Una Mirada al Mundo Fungi', '1 día', 'Caminata micológica en el bosque y taller gastronómico a base de hongos con la comunidad.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p10', 'Yatini', '2 días', 'Rutas de alta montaña y senderos históricos: travesía exigente con cambios de ecosistema, convivencia comunitaria y hospedaje en cabañas.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p11', 'Yaa Cuetzi', '2 días', 'Senderos de valor histórico y paisajes de montaña con miradores panorámicos, convivencia comunitaria y hospedaje en cabañas.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p12', 'Yaa – Gatzi', '2 días', 'Antiguas minas y senderos de montaña entre comunidades, combinando naturaleza, historia y cultura local.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p13', 'Valle Encantado', '2 días', 'Rutas históricas prehispánicas y vestigios coloniales, combinando senderismo, paisaje y contenido cultural.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p14', 'Sierra Norte Imperdible', '2 días', 'Senderos de montaña con miradores y formaciones rocosas, combinando paisajes naturales con actividades de aventura.', 1800, '2026-07-11', '2026-07-12', 'En Curso', 'Español / Inglés', 'Van'),
  ('p15', 'Senderos en el Aire', '2 días', 'Senderismo entre comunidades, actividades de aventura (puentes colgantes y tirolesas) y conocimiento de plantas medicinales.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p16', 'Latzi Belli', '2 días', 'Caminos rurales entre comunidades, paisajes de montaña y cambios de ecosistema, con visitas productivas y hospedaje en cabañas.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p17', 'El Paraíso de las Nubes', '2 días', 'Bosques de pino-encino y cascadas, con caminatas al amanecer y taller de pan tradicional.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p18', 'Bosques con Encanto', '2 días', 'Con base en Latuvi: senderos de montaña como Piedra del Corredor y la cascada El Molcajete, degustación de bebidas tradicionales y opción de temazcal.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p19', 'Una Ventura de Altura', '3 días', 'Senderismo entre comunidades, miradores panorámicos y actividades de aventura (puente colgante y tirolesa de 1 km).', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p20', 'Pasos Cortos pero Firmes', '3 días', 'Bosques, cascadas y paisajes de montaña, con elaboración de pan, plantas medicinales y cierre en miradores panorámicos.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p21', 'Pasos con Historia', '3 días', 'Rutas entre Llano Grande, Cuajimoloyas y San Miguel Amatlán: Cueva Iglesia, travesía Yatini y exploración de antiguas minas.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p22', 'Herencia de una Tierra Viva', '3 días', 'Senderismo entre Benito Juárez, La Nevería y Latuvi, con talleres gastronómicos del maíz y bebidas tradicionales.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p23', 'Entre Hojas y Ríos', '3 días', 'Travesía entre Cuajimoloyas, Latuvi y Amatlán: bosques de pino-encino, Camino Real, vestigios prehispánicos, minas y ex haciendas.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p24', 'Colores de Mi Tierra', '3 días', 'Con base en Lachatao: Camino Real, vestigios prehispánicos y circuito Los Molinos con miradores, ríos y espacios recreativos.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p25', 'Caminos Reales', '3 días', 'Travesía entre Amatlán, Latuvi y Benito Juárez por el Camino Real, bosques de alta montaña y zonas de gran riqueza biológica.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p26', 'Tierra y Tradiciones', '4 días', 'Senderismo entre Cuajimoloyas, Benito Juárez y La Nevería, con talleres de cocina tradicional, conocimiento del maíz y medicina ancestral.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p27', 'Senderos Zapotecas', '4 días', 'Travesía entre Llano Grande, Cuajimoloyas, Latuvi y Benito Juárez por Cueva Iglesia y el Camino Real. Nota: se elige Amatlán o Lachatao de manera uniforme por ventas, no es fijo.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p28', 'Senderos con Encanto', '4 días', 'Senderos de montaña entre Llano Grande, Cuajimoloyas, Benito Juárez y La Nevería, con taller de pan tradicional y temazcal.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p29', 'Pueblos con Magia', '4 días', 'Naturaleza, cultura y aventura: caminatas entre bosques y ríos, temazcal, talleres de cocina tradicional y sitios históricos mineros.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p30', 'Rutas de la Naturaleza', '5 días', 'Caminatas entre bosques de pino-encino, miradores, puentes colgantes y el Camino Real, con cambio constante de ecosistemas y rutas de historia minera.', 1800, '2026-07-20', '2026-07-24', 'Confirmado', 'Español / Inglés', 'Van'),
  ('p31', 'Sierra Extrema', '5 días', 'La travesía de mayor exigencia: Cueva Iglesia, Yatini (26 km), Camino Real y La Cucharilla, con cierre en El Calvario.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van'),
  ('p32', 'Al Corazón del Mancomún', '7 días', 'Inmersión total en la Sierra Norte conectando Llano Grande, Cuajimoloyas, Benito Juárez, La Nevería, Latuvi y Lachatao/Amatlán a través de senderos, Camino Real, puentes colgantes y antiguas minas.', 2500, '2026-07-15', '2026-07-22', 'En Curso', 'Español / Inglés', 'Van'),
  ('p33', 'Servicios Individuales', 'Servicios', 'Servicios que se venden por separado o se agregan a cualquier paquete. Cada servicio se cotiza por unidad y se liquida directo con el prestador de la comunidad.', 0, null, null, 'Planeación', 'Español / Inglés', 'Van')
on conflict (id) do update set nombre=excluded.nombre, descripcion=excluded.descripcion;

-- COMUNIDADES DE CADA PAQUETE
insert into paquete_comunidades (paquete_id, comunidad_id, orden) values
  ('p01', 'cuajimoloyas', 0),
  ('p02', 'cuajimoloyas', 0),
  ('p03', 'benito_juarez', 0),
  ('p04', 'capulalpam', 0),
  ('p05', 'amatlan', 0),
  ('p06', 'cuajimoloyas', 0),
  ('p06', 'san_miguel_del_valle', 1),
  ('p06', 'llano_grande', 2),
  ('p07', 'la_neveria', 0),
  ('p08', 'teotitlan_del_valle', 0),
  ('p08', 'benito_juarez', 1),
  ('p09', 'cuajimoloyas', 0),
  ('p10', 'amatlan', 0),
  ('p10', 'lachatao', 1),
  ('p10', 'latuvi', 2),
  ('p11', 'cuajimoloyas', 0),
  ('p12', 'amatlan', 0),
  ('p12', 'capulalpam', 1),
  ('p13', 'lachatao', 0),
  ('p14', 'cuajimoloyas', 0),
  ('p14', 'san_miguel_del_valle', 1),
  ('p14', 'llano_grande', 2),
  ('p15', 'benito_juarez', 0),
  ('p15', 'cuajimoloyas', 1),
  ('p16', 'benito_juarez', 0),
  ('p16', 'la_neveria', 1),
  ('p16', 'latuvi', 2),
  ('p17', 'llano_grande', 0),
  ('p17', 'cuajimoloyas', 1),
  ('p18', 'latuvi', 0),
  ('p19', 'benito_juarez', 0),
  ('p19', 'cuajimoloyas', 1),
  ('p20', 'llano_grande', 0),
  ('p20', 'cuajimoloyas', 1),
  ('p20', 'benito_juarez', 2),
  ('p21', 'llano_grande', 0),
  ('p21', 'san_miguel_del_valle', 1),
  ('p21', 'cuajimoloyas', 2),
  ('p21', 'amatlan', 3),
  ('p22', 'benito_juarez', 0),
  ('p22', 'la_neveria', 1),
  ('p22', 'latuvi', 2),
  ('p23', 'cuajimoloyas', 0),
  ('p23', 'latuvi', 1),
  ('p23', 'amatlan', 2),
  ('p24', 'lachatao', 0),
  ('p24', 'capulalpam', 1),
  ('p25', 'amatlan', 0),
  ('p25', 'lachatao', 1),
  ('p25', 'latuvi', 2),
  ('p25', 'benito_juarez', 3),
  ('p26', 'cuajimoloyas', 0),
  ('p26', 'benito_juarez', 1),
  ('p26', 'la_neveria', 2),
  ('p27', 'llano_grande', 0),
  ('p27', 'cuajimoloyas', 1),
  ('p27', 'amatlan', 2),
  ('p27', 'lachatao', 3),
  ('p27', 'latuvi', 4),
  ('p27', 'benito_juarez', 5),
  ('p28', 'llano_grande', 0),
  ('p28', 'cuajimoloyas', 1),
  ('p28', 'benito_juarez', 2),
  ('p28', 'la_neveria', 3),
  ('p29', 'capulalpam', 0),
  ('p29', 'lachatao', 1),
  ('p30', 'cuajimoloyas', 0),
  ('p30', 'benito_juarez', 1),
  ('p30', 'la_neveria', 2),
  ('p30', 'latuvi', 3),
  ('p30', 'lachatao', 4),
  ('p30', 'amatlan', 5),
  ('p31', 'san_miguel_del_valle', 0),
  ('p31', 'llano_grande', 1),
  ('p31', 'amatlan', 2),
  ('p31', 'lachatao', 3),
  ('p31', 'latuvi', 4),
  ('p31', 'cuajimoloyas', 5),
  ('p32', 'llano_grande', 0),
  ('p32', 'cuajimoloyas', 1),
  ('p32', 'benito_juarez', 2),
  ('p32', 'la_neveria', 3),
  ('p32', 'latuvi', 4),
  ('p32', 'lachatao', 5),
  ('p32', 'amatlan', 6),
  ('p33', 'cuajimoloyas', 0),
  ('p33', 'benito_juarez', 1),
  ('p33', 'llano_grande', 2),
  ('p33', 'la_neveria', 3),
  ('p33', 'latuvi', 4),
  ('p33', 'lachatao', 5),
  ('p33', 'amatlan', 6),
  ('p33', 'capulalpam', 7)
on conflict do nothing;

-- ITINERARIO (días e items, con su tipo de liquidación)
with d as (
  insert into itinerario_dias (paquete_id, dia, recorrido) values
    ('p01', 1, 'Cuajimoloyas'),
    ('p02', 1, 'Cuajimoloyas'),
    ('p03', 1, 'Benito Juárez'),
    ('p04', 1, 'Capulálpam'),
    ('p05', 1, 'Amatlán'),
    ('p06', 1, 'Cuajimoloyas → San Miguel del Valle → Llano Grande'),
    ('p07', 1, 'La Nevería'),
    ('p08', 1, 'Teotitlán del Valle → Benito Juárez'),
    ('p09', 1, 'Cuajimoloyas'),
    ('p10', 1, 'Amatlán'),
    ('p10', 2, 'Lachatao / Latuvi'),
    ('p11', 1, 'Cuajimoloyas'),
    ('p11', 2, 'Cuajimoloyas'),
    ('p12', 1, 'Amatlán'),
    ('p12', 2, 'Amatlán → Capulálpam'),
    ('p13', 1, 'Lachatao'),
    ('p13', 2, 'Lachatao'),
    ('p14', 1, 'San Miguel del Valle → Llano Grande'),
    ('p14', 2, 'Cuajimoloyas'),
    ('p15', 1, 'Benito Juárez'),
    ('p15', 2, 'Benito Juárez → Cuajimoloyas'),
    ('p16', 1, 'Benito Juárez → La Nevería'),
    ('p16', 2, 'La Nevería → Latuvi'),
    ('p17', 1, 'Llano Grande'),
    ('p17', 2, 'Llano Grande → Cuajimoloyas'),
    ('p18', 1, 'Latuvi'),
    ('p18', 2, 'Latuvi'),
    ('p19', 1, 'Benito Juárez'),
    ('p19', 2, 'Benito Juárez → Cuajimoloyas'),
    ('p19', 3, 'Cuajimoloyas'),
    ('p20', 1, 'Llano Grande'),
    ('p20', 2, 'Llano Grande → Cuajimoloyas'),
    ('p20', 3, 'Cuajimoloyas → Benito Juárez'),
    ('p21', 1, 'Llano Grande → San Miguel del Valle → Cuajimoloyas'),
    ('p21', 2, 'Cuajimoloyas → Amatlán'),
    ('p21', 3, 'Amatlán'),
    ('p22', 1, 'Benito Juárez'),
    ('p22', 2, 'Benito Juárez → La Nevería'),
    ('p22', 3, 'La Nevería → Latuvi'),
    ('p23', 1, 'Cuajimoloyas → Latuvi'),
    ('p23', 2, 'Latuvi → Amatlán'),
    ('p23', 3, 'Amatlán'),
    ('p24', 1, 'Lachatao'),
    ('p24', 2, 'Lachatao → Capulálpam'),
    ('p24', 3, 'Capulálpam'),
    ('p25', 1, 'Amatlán'),
    ('p25', 2, 'Lachatao → Latuvi'),
    ('p25', 3, 'Latuvi → Benito Juárez'),
    ('p26', 1, 'Cuajimoloyas'),
    ('p26', 2, 'Cuajimoloyas → Benito Juárez'),
    ('p26', 3, 'Benito Juárez → La Nevería'),
    ('p26', 4, 'La Nevería'),
    ('p27', 1, 'Llano Grande → Cuajimoloyas'),
    ('p27', 2, 'Cuajimoloyas → Amatlán / Lachatao'),
    ('p27', 3, 'Lachatao → Latuvi'),
    ('p27', 4, 'Latuvi → Benito Juárez'),
    ('p28', 1, 'Llano Grande'),
    ('p28', 2, 'Llano Grande → Cuajimoloyas'),
    ('p28', 3, 'Cuajimoloyas → Benito Juárez'),
    ('p28', 4, 'Benito Juárez → La Nevería'),
    ('p29', 1, 'Capulálpam'),
    ('p29', 2, 'Capulálpam'),
    ('p29', 3, 'Capulálpam → Lachatao'),
    ('p29', 4, 'Lachatao'),
    ('p30', 1, 'Cuajimoloyas → Benito Juárez'),
    ('p30', 2, 'Benito Juárez → La Nevería'),
    ('p30', 3, 'La Nevería → Latuvi'),
    ('p30', 4, 'Latuvi → Lachatao'),
    ('p30', 5, 'Amatlán / Lachatao'),
    ('p31', 1, 'San Miguel del Valle → Llano Grande'),
    ('p31', 2, 'Llano Grande → Amatlán'),
    ('p31', 3, 'Lachatao → Latuvi'),
    ('p31', 4, 'Latuvi → Cuajimoloyas'),
    ('p31', 5, 'Cuajimoloyas'),
    ('p32', 1, 'Llano Grande'),
    ('p32', 2, 'Llano Grande → Cuajimoloyas'),
    ('p32', 3, 'Cuajimoloyas → Benito Juárez'),
    ('p32', 4, 'Benito Juárez → La Nevería'),
    ('p32', 5, 'La Nevería → Latuvi'),
    ('p32', 6, 'Latuvi → Lachatao'),
    ('p32', 7, 'Amatlán')
  on conflict (paquete_id, dia) do update set recorrido = excluded.recorrido
  returning id, paquete_id, dia
)
insert into itinerario_items (dia_id, orden, texto, tipo, comunidad_id, monto, por_persona)
select d.id, v.orden, v.texto, v.tipo::tipo_liquidacion, v.comunidad_id, 0, v.por_persona
from d join (values
  ('p01', 1, 0, 'Sendero – Cañón del Coyote · 5 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p01', 1, 1, 'Puente colgante', 'Actividad', 'cuajimoloyas', true),
  ('p02', 1, 0, 'Sendero – Mirador El Calvario · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p02', 1, 1, 'Puente colgante', 'Actividad', 'cuajimoloyas', true),
  ('p03', 1, 0, 'Taller gastronómico en la Granja del Señor Elí', 'Taller', 'benito_juarez', true),
  ('p03', 1, 1, 'Sendero: caminata y visita al Mirador', 'Sendero', 'benito_juarez', false),
  ('p03', 1, 2, 'Puente colgante', 'Actividad', 'benito_juarez', true),
  ('p04', 1, 0, 'Sendero – Los Molinos · 8 km · 3 h', 'Sendero', 'capulalpam', false),
  ('p05', 1, 0, 'Sendero – Las Minas · 8 km · 3 h', 'Sendero', 'amatlan', false),
  ('p06', 1, 0, 'Sendero – Cueva Iglesia · 12 km · 5 h', 'Sendero', 'cuajimoloyas', false),
  ('p07', 1, 1, 'Recorrido – Los Colores del Maíz', 'Sendero', 'la_neveria', false),
  ('p07', 1, 2, 'Taller gastronómico a base de maíz con familia local', 'Taller', 'la_neveria', true),
  ('p08', 1, 1, 'Observación de aves', 'Actividad', 'teotitlan_del_valle', true),
  ('p09', 1, 0, 'Caminata en el bosque (Señora Martha) · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p09', 1, 1, 'Taller gastronómico a base de hongos – Señora Martha', 'Taller', 'cuajimoloyas', true),
  ('p09', 1, 2, 'Puente colgante', 'Actividad', 'cuajimoloyas', true),
  ('p10', 1, 0, 'Sendero – Ruta Yatini · 23 km · 6-7 h', 'Sendero', 'amatlan', false),
  ('p10', 1, 3, 'Hospedaje en cabañas Amatlán', 'Hospedaje', 'amatlan', false),
  ('p10', 2, 1, 'Sendero – Camino Real de Lachatao a Latuvi · 16 km · 5-6 h', 'Sendero', 'lachatao', false),
  ('p11', 1, 0, 'Sendero – Ruta Xinudaa · 17 km · 5-6 h', 'Sendero', 'cuajimoloyas', false),
  ('p11', 1, 3, 'Cena: Restaurante el Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p11', 1, 4, 'Hospedaje en cabañas Cuajimoloyas', 'Hospedaje', 'cuajimoloyas', false),
  ('p11', 2, 0, 'Desayuno: Restaurante el Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p11', 2, 1, 'Sendero – Ruta El Calvario · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p11', 2, 2, 'Puente colgante', 'Actividad', 'cuajimoloyas', true),
  ('p12', 1, 0, 'Sendero – Ruta Las Minas · 12 km · 4 h', 'Sendero', 'amatlan', false),
  ('p12', 1, 2, 'Acceso al museo de Amatlán', 'Actividad', 'amatlan', true),
  ('p12', 1, 4, 'Hospedaje en cabañas Amatlán', 'Hospedaje', 'amatlan', false),
  ('p12', 2, 1, 'Sendero – Tierra Caliente de Amatlán a Capulálpam · 12 km · 4 h', 'Sendero', 'amatlan', false),
  ('p13', 1, 0, 'Sendero – Ruta La Virgen · 12 km · 4-5 h', 'Sendero', 'lachatao', false),
  ('p13', 1, 3, 'Hospedaje en cabañas Lachatao', 'Hospedaje', 'lachatao', false),
  ('p13', 2, 1, 'Sendero – Ruta 5 Señores · 14 km · 4-5 h', 'Sendero', 'lachatao', false),
  ('p14', 1, 0, 'Sendero – Ruta Cueva Iglesia · 12 km · 4-5 h', 'Sendero', 'san_miguel_del_valle', false),
  ('p14', 1, 3, 'Cena: Restaurante Mirador', 'Actividad', 'san_miguel_del_valle', true),
  ('p14', 1, 4, 'Hospedaje en cabañas Cuajimoloyas', 'Hospedaje', 'san_miguel_del_valle', false),
  ('p14', 2, 1, 'Sendero – Ruta Cañón del Coyote · 5 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p14', 2, 2, 'Puente colgante', 'Actividad', 'cuajimoloyas', true),
  ('p15', 1, 0, 'Sendero – Caminata al Mirador · 5 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p15', 1, 1, 'Puente colgante y línea de 3 tirolesas en el Mirador', 'Actividad', 'benito_juarez', true),
  ('p15', 1, 4, 'Hospedaje en cabañas Benito Juárez', 'Hospedaje', 'benito_juarez', false),
  ('p15', 2, 1, 'Sendero – Benito Juárez a Cuaji · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p15', 2, 2, 'Plantas medicinales con degustación de té – Esther', 'Taller', 'benito_juarez', true),
  ('p15', 2, 3, 'Puente colgante Cuaji', 'Actividad', 'benito_juarez', true),
  ('p16', 1, 0, 'Sendero – Benito Juárez a La Nevería · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p16', 1, 1, 'Mirador y Puente Colgante', 'Actividad', 'benito_juarez', true),
  ('p16', 1, 2, 'Visita a los Invernaderos', 'Actividad', 'benito_juarez', true),
  ('p16', 1, 4, 'Hospedaje en cabañas Nevería', 'Hospedaje', 'benito_juarez', false),
  ('p16', 2, 1, 'Sendero – La Nevería a Latuvi · 12 km · 4 h', 'Sendero', 'la_neveria', false),
  ('p17', 1, 1, 'Sendero – Ruta El Pinovete · 8 km · 4 h', 'Sendero', 'llano_grande', false),
  ('p17', 1, 3, 'Taller de pan', 'Taller', 'llano_grande', true),
  ('p17', 1, 5, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p17', 2, 2, 'Sendero – Llano Grande a Cuaji · 8 km · 3 h', 'Sendero', 'llano_grande', false),
  ('p17', 2, 3, 'Puente colgante', 'Actividad', 'llano_grande', true),
  ('p18', 1, 0, 'Sendero – Ruta Piedra del Corredor · 16 km · 4-5 h', 'Sendero', 'latuvi', false),
  ('p18', 1, 3, 'Hospedaje en cabañas Latuvi', 'Hospedaje', 'latuvi', false),
  ('p18', 2, 1, 'Sendero – Ruta El Molcajete · 11 km · 4 h', 'Sendero', 'latuvi', false),
  ('p18', 2, 2, 'Taller de pan serrano', 'Taller', 'latuvi', true),
  ('p19', 1, 0, 'Sendero – Ruta El Mirador · 5 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p19', 1, 1, 'Accesos al puente colgante y pases para línea de 3 tirolesas', 'Actividad', 'benito_juarez', true),
  ('p19', 1, 3, 'Hospedaje en cabañas', 'Hospedaje', 'benito_juarez', false),
  ('p19', 2, 1, 'Sendero – Benito Juárez a Cuajimoloyas · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p19', 2, 2, 'Puente colgante y pase para tirolesa de 1 km', 'Actividad', 'benito_juarez', true),
  ('p19', 2, 4, 'Cena: Restaurante Mirador', 'Actividad', 'benito_juarez', true),
  ('p19', 2, 5, 'Hospedaje en cabañas', 'Hospedaje', 'benito_juarez', false),
  ('p19', 3, 0, 'Desayuno: Restaurante el Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p19', 3, 1, 'Sendero – Ruta El Calvario · 6 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p20', 1, 0, 'Sendero – Ruta El Pinovete · 8 km · 3 h', 'Sendero', 'llano_grande', false),
  ('p20', 1, 2, 'Taller de pan', 'Taller', 'llano_grande', true),
  ('p20', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p20', 2, 1, 'Sendero – Llano Grande a Cuaji · 8 km · 3 h', 'Sendero', 'llano_grande', false),
  ('p20', 2, 3, 'Plantas medicinales con degustación de té – Esther', 'Taller', 'llano_grande', true),
  ('p20', 2, 4, 'Cena: El Mirador', 'Actividad', 'llano_grande', true),
  ('p20', 2, 5, 'Hospedaje en cabañas de Cuajimoloyas', 'Hospedaje', 'llano_grande', false),
  ('p20', 3, 1, 'Sendero – Cuajimoloyas a Benito Juárez · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p20', 3, 2, 'Acceso al Mirador y Puente Colgante de Benito Juárez', 'Actividad', 'cuajimoloyas', true),
  ('p21', 1, 0, 'Sendero – Ruta Cueva Iglesia · 12 km · 4-5 h', 'Sendero', 'llano_grande', false),
  ('p21', 1, 3, 'Cena: Restaurante Mirador', 'Actividad', 'llano_grande', true),
  ('p21', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p21', 2, 0, 'Desayuno: Restaurante Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p21', 2, 1, 'Sendero – Ruta Yatini · 23 km · 6-7 h', 'Sendero', 'cuajimoloyas', false),
  ('p21', 2, 4, 'Hospedaje en cabañas Amatlán', 'Hospedaje', 'cuajimoloyas', false),
  ('p21', 3, 1, 'Sendero – Ruta Las Minas · 14 km · 4-5 h', 'Sendero', 'amatlan', false),
  ('p22', 1, 0, 'Sendero – Caminata hacia la zona de Mirador', 'Sendero', 'benito_juarez', false),
  ('p22', 1, 1, 'Puente colgante', 'Actividad', 'benito_juarez', true),
  ('p22', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'benito_juarez', false),
  ('p22', 2, 1, 'Sendero – Benito Juárez a Nevería · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p22', 2, 3, 'Los Colores del Maíz: taller gastronómico y cena en casa de familia', 'Taller', 'benito_juarez', true),
  ('p22', 2, 4, 'Hospedaje en cabañas', 'Hospedaje', 'benito_juarez', false),
  ('p22', 3, 1, 'Sendero – Nevería a Latuvi · 12 km · 4 h', 'Sendero', 'la_neveria', false),
  ('p22', 3, 3, 'Taller de Pulque y Tepache', 'Taller', 'la_neveria', true),
  ('p23', 1, 0, 'Sendero – Caminata a Latuvi por la ruta Cucharilla · 16 km · 5-6 h', 'Sendero', 'cuajimoloyas', false),
  ('p23', 1, 1, 'Box lunch – Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p23', 1, 3, 'Hospedaje en cabañas', 'Hospedaje', 'cuajimoloyas', false),
  ('p23', 2, 1, 'Sendero – Latuvi a Amatlán por el Camino Real · 16 km · 5-6 h', 'Sendero', 'latuvi', false),
  ('p23', 2, 4, 'Hospedaje en cabañas Amatlán', 'Hospedaje', 'latuvi', false),
  ('p23', 3, 1, 'Sendero – Ruta Las Minas · 14 km · 4-5 h', 'Sendero', 'amatlan', false),
  ('p24', 1, 0, 'Sendero – Camino Real hasta el punto “La Virgen” · 12 km · 4.5 h', 'Sendero', 'lachatao', false),
  ('p24', 1, 2, 'Hospedaje en cabañas', 'Hospedaje', 'lachatao', false),
  ('p24', 2, 1, 'Sendero – Ruta 5 Señores · 14 km · 5 h', 'Sendero', 'lachatao', false),
  ('p24', 2, 5, 'Hospedaje en cabañas de Capulálpam', 'Hospedaje', 'lachatao', false),
  ('p24', 3, 1, 'Sendero – Ruta Los Molinos · 8 km · 3 h', 'Sendero', 'capulalpam', false),
  ('p25', 1, 0, 'Sendero – Ruta Las Minas · 14 km · 4 h', 'Sendero', 'amatlan', false),
  ('p25', 1, 2, 'Visita al museo de Amatlán', 'Actividad', 'amatlan', true),
  ('p25', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'amatlan', false),
  ('p25', 2, 1, 'Sendero – Lachatao a Latuvi por el Camino Real · 16 km · 5-6 h', 'Sendero', 'lachatao', false),
  ('p25', 2, 4, 'Taller de Pulque y tepache', 'Taller', 'lachatao', true),
  ('p25', 2, 6, 'Hospedaje en cabañas', 'Hospedaje', 'lachatao', false),
  ('p25', 3, 1, 'Sendero – Latuvi a Benito Juárez · 12 km · 4.5 h', 'Sendero', 'latuvi', false),
  ('p25', 3, 2, 'Acceso al mirador y puente colgante', 'Actividad', 'latuvi', true),
  ('p26', 1, 0, 'Taller gastronómico y comida – Sra. Martha', 'Taller', 'cuajimoloyas', true),
  ('p26', 1, 1, 'Sendero – Ruta El Calvario · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p26', 1, 2, 'Acceso al puente colgante de Cuaji', 'Actividad', 'cuajimoloyas', true),
  ('p26', 1, 3, 'Cena: el Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p26', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'cuajimoloyas', false),
  ('p26', 2, 0, 'Desayuno: Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p26', 2, 1, 'Sendero – Cuajimoloyas a Benito Juárez · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p26', 2, 2, 'Acceso al puente colgante de Benito', 'Actividad', 'cuajimoloyas', true),
  ('p26', 2, 5, 'Hospedaje en cabañas', 'Hospedaje', 'cuajimoloyas', false),
  ('p26', 3, 1, 'Sendero – Benito Juárez a Nevería · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p26', 3, 3, 'Temazcal o baño de asiento – Ing. Gaudencio', 'Actividad', 'benito_juarez', true),
  ('p26', 3, 5, 'Hospedaje en cabañas de Nevería', 'Hospedaje', 'benito_juarez', false),
  ('p26', 4, 1, 'Recorrido Los Colores del Maíz · 2 h', 'Sendero', 'la_neveria', false),
  ('p26', 4, 2, 'Taller Los Colores del Maíz (nixtamalización, tortillas)', 'Taller', 'la_neveria', true),
  ('p27', 1, 0, 'Sendero – Llano Grande a Cuajimoloyas por la ruta Cueva Iglesia · 12 km · 4-5 h', 'Sendero', 'llano_grande', false),
  ('p27', 1, 3, 'Puente colgante Cuaji', 'Actividad', 'llano_grande', true),
  ('p27', 1, 4, 'Cena: el Mirador', 'Actividad', 'llano_grande', true),
  ('p27', 1, 5, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p27', 2, 0, 'Desayuno: Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p27', 2, 1, 'Sendero – Amatlán/Lachatao por la ruta Yatini · 23 km · 6-7 h', 'Sendero', 'cuajimoloyas', false),
  ('p27', 2, 2, 'Box Lunch – Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p27', 2, 4, 'Hospedaje en cabañas de Amatlán/Lachatao', 'Hospedaje', 'cuajimoloyas', false),
  ('p27', 3, 1, 'Sendero – Lachatao a Latuvi por Camino Real · 16 km · 5-6 h', 'Sendero', 'lachatao', false),
  ('p27', 3, 5, 'Hospedaje en cabañas de Latuvi', 'Hospedaje', 'lachatao', false),
  ('p27', 4, 1, 'Sendero – Latuvi a Benito Juárez · 12 km · 4 h', 'Sendero', 'latuvi', false),
  ('p27', 4, 2, 'Accesos a Mirador y Puente colgante Benito Juárez', 'Actividad', 'latuvi', true),
  ('p28', 1, 0, 'Sendero – Ruta La Sepultura · 12 km · 4 h', 'Sendero', 'llano_grande', false),
  ('p28', 1, 2, 'Taller de pan', 'Taller', 'llano_grande', true),
  ('p28', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p28', 2, 1, 'Sendero – Llano Grande a Cuajimoloyas · 8 km · 3 h', 'Sendero', 'llano_grande', false),
  ('p28', 2, 3, 'Acceso al Puente Colgante', 'Actividad', 'llano_grande', true),
  ('p28', 2, 4, 'Temazcal – Soledad', 'Actividad', 'llano_grande', true),
  ('p28', 2, 5, 'Cena: Mirador', 'Actividad', 'llano_grande', true),
  ('p28', 2, 6, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p28', 3, 0, 'Desayuno: Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p28', 3, 1, 'Sendero – Cuajimoloyas a Benito Juárez pasando por el puente colgante · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p28', 3, 4, 'Hospedaje en cabañas de Benito Juárez', 'Hospedaje', 'cuajimoloyas', false),
  ('p28', 4, 1, 'Sendero – Benito Juárez a Nevería · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p28', 4, 3, 'Visita a los invernaderos', 'Actividad', 'benito_juarez', true),
  ('p29', 1, 0, 'Sendero – Caminata a los Molinos · 8 km · 3 h', 'Sendero', 'capulalpam', false),
  ('p29', 1, 2, 'Visita a Cueva de arroyos', 'Actividad', 'capulalpam', true),
  ('p29', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'capulalpam', false),
  ('p29', 2, 1, 'Sendero – Ruta “Embudo” · 18 km · 5-6 h', 'Sendero', 'capulalpam', false),
  ('p29', 2, 3, 'Temazcal – Manos que Curan', 'Actividad', 'capulalpam', true),
  ('p29', 2, 5, 'Hospedaje en cabañas de Capulálpam', 'Hospedaje', 'capulalpam', false),
  ('p29', 3, 2, 'Taller gastronómico de Chichilo', 'Taller', 'capulalpam', true),
  ('p29', 3, 4, 'Sendero – Ruta Cerro del Jaguar', 'Sendero', 'capulalpam', false),
  ('p29', 3, 6, 'Hospedaje en cabañas', 'Hospedaje', 'capulalpam', false),
  ('p29', 4, 1, 'Sendero – Ruta ex hacienda 5 Señores · 14 km · 4 h', 'Sendero', 'lachatao', false),
  ('p30', 1, 0, 'Sendero – Cuajimoloyas a Benito Juárez · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p30', 1, 1, 'Acceso al Puente Colgante', 'Actividad', 'cuajimoloyas', true),
  ('p30', 1, 4, 'Hospedaje en cabañas', 'Hospedaje', 'cuajimoloyas', false),
  ('p30', 2, 1, 'Sendero – Benito Juárez a Nevería · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p30', 2, 3, 'Hospedaje en cabañas', 'Hospedaje', 'benito_juarez', false),
  ('p30', 3, 1, 'Sendero – Nevería a Latuvi · 12 km · 4 h', 'Sendero', 'la_neveria', false),
  ('p30', 3, 3, 'Hospedaje en cabañas', 'Hospedaje', 'la_neveria', false),
  ('p30', 4, 1, 'Sendero – Latuvi a Lachatao por Camino Real · 16 km · 5-6 h', 'Sendero', 'latuvi', false),
  ('p30', 4, 4, 'Hospedaje en cabañas', 'Hospedaje', 'latuvi', false),
  ('p30', 5, 1, 'Sendero – Ruta Las Minas · 12 km · 4 h', 'Sendero', 'amatlan', false),
  ('p31', 1, 0, 'Sendero – Ruta Cueva Iglesia · 12 km · 4-5 h', 'Sendero', 'san_miguel_del_valle', false),
  ('p31', 1, 3, 'Hospedaje en cabañas', 'Hospedaje', 'san_miguel_del_valle', false),
  ('p31', 2, 1, 'Sendero – Ruta Yatini · 26 km · 6-7 h', 'Sendero', 'llano_grande', false),
  ('p31', 2, 4, 'Hospedaje en cabañas', 'Hospedaje', 'llano_grande', false),
  ('p31', 3, 1, 'Sendero – Lachatao a Latuvi Camino Real · 16 km · 5-6 h', 'Sendero', 'lachatao', false),
  ('p31', 3, 4, 'Hospedaje en cabañas', 'Hospedaje', 'lachatao', false),
  ('p31', 4, 1, 'Sendero – Ruta La Cucharilla · 16 km · 5-6 h', 'Sendero', 'latuvi', false),
  ('p31', 4, 3, 'Cena: Comedor el Mirador', 'Actividad', 'latuvi', true),
  ('p31', 4, 4, 'Hospedaje en cabañas', 'Hospedaje', 'latuvi', false),
  ('p31', 5, 0, 'Desayuno: Comedor el Mirador', 'Actividad', 'cuajimoloyas', true),
  ('p31', 5, 1, 'Sendero – Ruta El Calvario · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p32', 1, 0, 'Sendero – Ruta La Sepultura · 12 km · 4 h', 'Sendero', 'llano_grande', false),
  ('p32', 1, 2, 'Taller de pan serrano', 'Taller', 'llano_grande', true),
  ('p32', 1, 4, 'Hospedaje en cabaña', 'Hospedaje', 'llano_grande', false),
  ('p32', 2, 1, 'Sendero – Llano Grande a Cuajimoloyas · 8 km · 3 h', 'Sendero', 'llano_grande', false),
  ('p32', 2, 3, 'Plantas medicinales con degustación de té – Esther', 'Taller', 'llano_grande', true),
  ('p32', 2, 4, 'Cena: Restaurante Mirador', 'Actividad', 'llano_grande', true),
  ('p32', 2, 5, 'Hospedaje en cabaña', 'Hospedaje', 'llano_grande', false),
  ('p32', 3, 1, 'Sendero – Cuajimoloyas a Benito Juárez · 8 km · 3 h', 'Sendero', 'cuajimoloyas', false),
  ('p32', 3, 3, 'Mirador y puente colgante', 'Actividad', 'cuajimoloyas', true),
  ('p32', 3, 5, 'Hospedaje en cabaña', 'Hospedaje', 'cuajimoloyas', false),
  ('p32', 4, 1, 'Sendero – Benito Juárez a Nevería · 8 km · 3 h', 'Sendero', 'benito_juarez', false),
  ('p32', 4, 3, 'Taller gastronómico y cena con una familia local', 'Taller', 'benito_juarez', true),
  ('p32', 4, 4, 'Hospedaje en cabaña', 'Hospedaje', 'benito_juarez', false),
  ('p32', 5, 1, 'Sendero – Nevería a Latuvi · 12 km · 4 h', 'Sendero', 'la_neveria', false),
  ('p32', 5, 3, 'Hospedaje en cabaña', 'Hospedaje', 'la_neveria', false),
  ('p32', 6, 1, 'Sendero – Latuvi a Lachatao por el Camino Real', 'Sendero', 'latuvi', false),
  ('p32', 6, 5, 'Hospedaje en cabaña Amatlán', 'Hospedaje', 'latuvi', false),
  ('p32', 7, 1, 'Sendero – Ruta Las Minas · 14 km · 3-4 h', 'Sendero', 'amatlan', false)
) as v(paquete_id, dia, orden, texto, tipo, comunidad_id, por_persona)
  on v.paquete_id = d.paquete_id and v.dia = d.dia;

-- COMEDORES (se liquidan DIRECTO; el monto es POR PERSONA)
insert into comedores (paquete_id, dia, comunidad_id, recorrido, nombre, tipo, monto_por_persona) values
  ('p01', 1, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p02', 1, 'cuajimoloyas', 'Cuajimoloyas', 'Comida/Truchas', 'Comida', 0),
  ('p03', 1, 'benito_juarez', 'Benito Juárez', 'Granja del Señor Elí', 'Comida', 0),
  ('p04', 1, 'capulalpam', 'Capulálpam', 'Comida en Los Molinos', 'Comida', 0),
  ('p05', 1, 'amatlan', 'Amatlán', 'Comida/Truchas en el Rescate', 'Comida', 0),
  ('p06', 1, 'cuajimoloyas', 'Cuajimoloyas → San Miguel del Valle → Llano Grande', 'Por definir', 'Box lunch', 0),
  ('p06', 1, 'cuajimoloyas', 'Cuajimoloyas → San Miguel del Valle → Llano Grande', 'en Llano Grande', 'Comida', 0),
  ('p07', 1, 'la_neveria', 'La Nevería', 'Comedor de Nevería', 'Desayuno', 0),
  ('p07', 1, 'la_neveria', 'La Nevería', 'con familia local', 'Comida', 0),
  ('p08', 1, 'teotitlan_del_valle', 'Teotitlán del Valle → Benito Juárez', 'en Teotitlán', 'Desayuno', 0),
  ('p08', 1, 'teotitlan_del_valle', 'Teotitlán del Valle → Benito Juárez', 'comedor del pueblo Benito Juárez', 'Comida', 0),
  ('p10', 1, 'amatlan', 'Amatlán', 'Por definir', 'Box lunch', 0),
  ('p10', 1, 'amatlan', 'Amatlán', 'Por definir', 'Comida', 0),
  ('p10', 1, 'amatlan', 'Amatlán', 'Por definir', 'Cena', 0),
  ('p10', 2, 'lachatao', 'Lachatao / Latuvi', 'Por definir', 'Desayuno', 0),
  ('p10', 2, 'lachatao', 'Lachatao / Latuvi', 'Por definir', 'Box lunch', 0),
  ('p10', 2, 'lachatao', 'Lachatao / Latuvi', 'Eco Latuvi', 'Comida', 0),
  ('p11', 1, 'cuajimoloyas', 'Cuajimoloyas', 'Por definir', 'Box lunch', 0),
  ('p11', 1, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p11', 1, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante el Mirador', 'Cena', 0),
  ('p11', 2, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante el Mirador', 'Desayuno', 0),
  ('p11', 2, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p12', 1, 'amatlan', 'Amatlán', 'Comida/Trucha en el Rescate', 'Comida', 0),
  ('p12', 1, 'amatlan', 'Amatlán', 'Por definir', 'Cena', 0),
  ('p12', 2, 'amatlan', 'Amatlán → Capulálpam', 'Por definir', 'Desayuno', 0),
  ('p12', 2, 'amatlan', 'Amatlán → Capulálpam', 'Comida/Trucha en Los Molinos', 'Comida', 0),
  ('p13', 1, 'lachatao', 'Lachatao', 'Por definir', 'Box lunch', 0),
  ('p13', 1, 'lachatao', 'Lachatao', 'Por definir', 'Comida', 0),
  ('p13', 1, 'lachatao', 'Lachatao', 'Por definir', 'Cena', 0),
  ('p13', 2, 'lachatao', 'Lachatao', 'Por definir', 'Desayuno', 0),
  ('p13', 2, 'lachatao', 'Lachatao', 'Por definir', 'Comida', 0),
  ('p14', 1, 'san_miguel_del_valle', 'San Miguel del Valle → Llano Grande', 'Karla', 'Box lunch', 0),
  ('p14', 1, 'san_miguel_del_valle', 'San Miguel del Valle → Llano Grande', 'Restaurante Marlen', 'Comida', 0),
  ('p14', 1, 'san_miguel_del_valle', 'San Miguel del Valle → Llano Grande', 'Restaurante Mirador', 'Cena', 0),
  ('p14', 2, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante', 'Desayuno', 0),
  ('p14', 2, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p15', 1, 'benito_juarez', 'Benito Juárez', 'Familia', 'Comida', 0),
  ('p15', 1, 'benito_juarez', 'Benito Juárez', 'Comedor del pueblo', 'Cena', 0),
  ('p15', 2, 'benito_juarez', 'Benito Juárez → Cuajimoloyas', 'Comedor del Pueblo', 'Desayuno', 0),
  ('p15', 2, 'benito_juarez', 'Benito Juárez → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p16', 1, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Comida', 0),
  ('p16', 1, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Cena', 0),
  ('p16', 2, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p16', 2, 'la_neveria', 'La Nevería → Latuvi', 'en Latuvi', 'Comida', 0),
  ('p17', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Desayuno', 0),
  ('p17', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Comida', 0),
  ('p17', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Cena', 0),
  ('p17', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p18', 1, 'latuvi', 'Latuvi', 'Por definir', 'Box lunch', 0),
  ('p18', 1, 'latuvi', 'Latuvi', 'Por definir', 'Comida', 0),
  ('p18', 1, 'latuvi', 'Latuvi', 'Por definir', 'Cena', 0),
  ('p18', 2, 'latuvi', 'Latuvi', 'Por definir', 'Desayuno', 0),
  ('p18', 2, 'latuvi', 'Latuvi', 'Por definir', 'Comida', 0),
  ('p19', 1, 'benito_juarez', 'Benito Juárez', 'Por definir', 'Comida', 0),
  ('p19', 1, 'benito_juarez', 'Benito Juárez', 'Por definir', 'Cena', 0),
  ('p19', 2, 'benito_juarez', 'Benito Juárez → Cuajimoloyas', 'Por definir', 'Desayuno', 0),
  ('p19', 2, 'benito_juarez', 'Benito Juárez → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p19', 2, 'benito_juarez', 'Benito Juárez → Cuajimoloyas', 'Restaurante Mirador', 'Cena', 0),
  ('p19', 3, 'cuajimoloyas', 'Cuajimoloyas', 'Restaurante el Mirador', 'Desayuno', 0),
  ('p19', 3, 'cuajimoloyas', 'Cuajimoloyas', 'Por definir', 'Comida', 0),
  ('p20', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Comida', 0),
  ('p20', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Cena', 0),
  ('p20', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Por definir', 'Desayuno', 0),
  ('p20', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p20', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'El Mirador', 'Cena', 0),
  ('p20', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Por definir', 'Desayuno', 0),
  ('p20', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Comedor del Pueblo', 'Comida', 0),
  ('p21', 1, 'llano_grande', 'Llano Grande → San Miguel del Valle → Cuajimoloyas', 'Por definir', 'Box lunch', 0),
  ('p21', 1, 'llano_grande', 'Llano Grande → San Miguel del Valle → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p21', 1, 'llano_grande', 'Llano Grande → San Miguel del Valle → Cuajimoloyas', 'Restaurante Mirador', 'Cena', 0),
  ('p21', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán', 'Restaurante Mirador', 'Desayuno', 0),
  ('p21', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán', 'Por definir', 'Box lunch', 0),
  ('p21', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán', 'Por definir', 'Comida', 0),
  ('p21', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán', 'Por definir', 'Cena', 0),
  ('p21', 3, 'amatlan', 'Amatlán', 'Por definir', 'Desayuno', 0),
  ('p21', 3, 'amatlan', 'Amatlán', 'Comida/Truchas', 'Comida', 0),
  ('p22', 1, 'benito_juarez', 'Benito Juárez', 'en la Granja del Señor Elí', 'Comida', 0),
  ('p22', 1, 'benito_juarez', 'Benito Juárez', 'Comedor del Pueblo', 'Cena', 0),
  ('p22', 2, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Desayuno', 0),
  ('p22', 2, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Comida', 0),
  ('p22', 3, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p22', 3, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Comida', 0),
  ('p23', 1, 'cuajimoloyas', 'Cuajimoloyas → Latuvi', 'Mirador', 'Box lunch', 0),
  ('p23', 1, 'cuajimoloyas', 'Cuajimoloyas → Latuvi', 'Por definir', 'Comida', 0),
  ('p23', 1, 'cuajimoloyas', 'Cuajimoloyas → Latuvi', 'Por definir', 'Cena', 0),
  ('p23', 2, 'latuvi', 'Latuvi → Amatlán', 'Por definir', 'Desayuno', 0),
  ('p23', 2, 'latuvi', 'Latuvi → Amatlán', 'Por definir', 'Box lunch', 0),
  ('p23', 2, 'latuvi', 'Latuvi → Amatlán', 'Por definir', 'Comida', 0),
  ('p23', 2, 'latuvi', 'Latuvi → Amatlán', 'Por definir', 'Cena', 0),
  ('p23', 3, 'amatlan', 'Amatlán', 'Por definir', 'Desayuno', 0),
  ('p23', 3, 'amatlan', 'Amatlán', 'Comida/Truchas', 'Comida', 0),
  ('p24', 1, 'lachatao', 'Lachatao', 'Por definir', 'Comida', 0),
  ('p24', 1, 'lachatao', 'Lachatao', 'Por definir', 'Cena', 0),
  ('p24', 2, 'lachatao', 'Lachatao → Capulálpam', 'Por definir', 'Desayuno', 0),
  ('p24', 2, 'lachatao', 'Lachatao → Capulálpam', 'Por definir', 'Comida', 0),
  ('p24', 2, 'lachatao', 'Lachatao → Capulálpam', 'Por definir', 'Cena', 0),
  ('p24', 3, 'capulalpam', 'Capulálpam', 'Por definir', 'Desayuno', 0),
  ('p24', 3, 'capulalpam', 'Capulálpam', 'Por definir', 'Comida', 0),
  ('p25', 1, 'amatlan', 'Amatlán', 'Comida/Truchas en el Rescate', 'Comida', 0),
  ('p25', 1, 'amatlan', 'Amatlán', 'Por definir', 'Cena', 0),
  ('p25', 2, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p25', 2, 'lachatao', 'Lachatao → Latuvi', 'Lachatao', 'Box lunch', 0),
  ('p25', 2, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Comida', 0),
  ('p25', 2, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Cena', 0),
  ('p25', 3, 'latuvi', 'Latuvi → Benito Juárez', 'Por definir', 'Desayuno', 0),
  ('p25', 3, 'latuvi', 'Latuvi → Benito Juárez', 'Por definir', 'Comida', 0),
  ('p26', 1, 'cuajimoloyas', 'Cuajimoloyas', 'el Mirador', 'Cena', 0),
  ('p26', 2, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Mirador', 'Desayuno', 0),
  ('p26', 2, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Por definir', 'Comida', 0),
  ('p26', 2, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Comedor del Pueblo', 'Cena', 0),
  ('p26', 3, 'benito_juarez', 'Benito Juárez → La Nevería', 'Comedor del Pueblo', 'Desayuno', 0),
  ('p26', 3, 'benito_juarez', 'Benito Juárez → La Nevería', 'Eco Nevería', 'Comida', 0),
  ('p26', 3, 'benito_juarez', 'Benito Juárez → La Nevería', 'Nevería', 'Cena', 0),
  ('p26', 4, 'la_neveria', 'La Nevería', 'Nevería', 'Desayuno', 0),
  ('p26', 4, 'la_neveria', 'La Nevería', 'Casa de familia', 'Cena', 0),
  ('p27', 1, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Karla', 'Box lunch', 0),
  ('p27', 1, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Comedor Marlen', 'Comida', 0),
  ('p27', 1, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'el Mirador', 'Cena', 0),
  ('p27', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán / Lachatao', 'Mirador', 'Desayuno', 0),
  ('p27', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán / Lachatao', 'Mirador', 'Box lunch', 0),
  ('p27', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán / Lachatao', 'Por definir', 'Comida', 0),
  ('p27', 2, 'cuajimoloyas', 'Cuajimoloyas → Amatlán / Lachatao', 'Por definir', 'Cena', 0),
  ('p27', 3, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p27', 3, 'lachatao', 'Lachatao → Latuvi', 'Lachatao', 'Box lunch', 0),
  ('p27', 3, 'lachatao', 'Lachatao → Latuvi', 'Eco Latuvi', 'Comida', 0),
  ('p27', 3, 'lachatao', 'Lachatao → Latuvi', 'Eco Latuvi', 'Cena', 0),
  ('p27', 4, 'latuvi', 'Latuvi → Benito Juárez', 'Latuvi', 'Desayuno', 0),
  ('p27', 4, 'latuvi', 'Latuvi → Benito Juárez', 'Por definir', 'Comida', 0),
  ('p28', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Comida', 0),
  ('p28', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Cena', 0),
  ('p28', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Por definir', 'Desayuno', 0),
  ('p28', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p28', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Mirador', 'Cena', 0),
  ('p28', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Mirador', 'Desayuno', 0),
  ('p28', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Granja del Señor Elí', 'Comida', 0),
  ('p28', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Comedor del Pueblo', 'Cena', 0),
  ('p28', 4, 'benito_juarez', 'Benito Juárez → La Nevería', 'Comedor del Pueblo', 'Desayuno', 0),
  ('p28', 4, 'benito_juarez', 'Benito Juárez → La Nevería', 'Nevería', 'Comida', 0),
  ('p29', 1, 'capulalpam', 'Capulálpam', 'Restaurante Los Molinos', 'Comida', 0),
  ('p29', 1, 'capulalpam', 'Capulálpam', 'Por definir', 'Cena', 0),
  ('p29', 2, 'capulalpam', 'Capulálpam', 'Por definir', 'Desayuno', 0),
  ('p29', 2, 'capulalpam', 'Capulálpam', 'Por definir', 'Comida', 0),
  ('p29', 2, 'capulalpam', 'Capulálpam', 'Por definir', 'Cena', 0),
  ('p29', 3, 'capulalpam', 'Capulálpam → Lachatao', 'Por definir', 'Desayuno', 0),
  ('p29', 3, 'capulalpam', 'Capulálpam → Lachatao', 'Por definir', 'Comida', 0),
  ('p29', 3, 'capulalpam', 'Capulálpam → Lachatao', 'Comedor del Pueblo', 'Cena', 0),
  ('p29', 4, 'lachatao', 'Lachatao', 'Por definir', 'Desayuno', 0),
  ('p29', 4, 'lachatao', 'Lachatao', 'Por definir', 'Comida', 0),
  ('p30', 1, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Granja el Señor Elí', 'Comida', 0),
  ('p30', 1, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Comedor del Pueblo', 'Cena', 0),
  ('p30', 2, 'benito_juarez', 'Benito Juárez → La Nevería', 'Comedor del pueblo', 'Desayuno', 0),
  ('p30', 2, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Comida', 0),
  ('p30', 2, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Cena', 0),
  ('p30', 3, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p30', 3, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Comida', 0),
  ('p30', 3, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Cena', 0),
  ('p30', 4, 'latuvi', 'Latuvi → Lachatao', 'Por definir', 'Desayuno', 0),
  ('p30', 4, 'latuvi', 'Latuvi → Lachatao', 'Lachatao', 'Comida', 0),
  ('p30', 4, 'latuvi', 'Latuvi → Lachatao', 'Por definir', 'Cena', 0),
  ('p30', 5, 'amatlan', 'Amatlán / Lachatao', 'Por definir', 'Desayuno', 0),
  ('p30', 5, 'amatlan', 'Amatlán / Lachatao', 'Comida/Truchas en el Rescate', 'Comida', 0),
  ('p31', 1, 'san_miguel_del_valle', 'San Miguel del Valle → Llano Grande', 'Karla', 'Box lunch', 0),
  ('p31', 1, 'san_miguel_del_valle', 'San Miguel del Valle → Llano Grande', 'Por definir', 'Cena', 0),
  ('p31', 2, 'llano_grande', 'Llano Grande → Amatlán', 'Por definir', 'Desayuno', 0),
  ('p31', 2, 'llano_grande', 'Llano Grande → Amatlán', 'Karla', 'Box lunch', 0),
  ('p31', 2, 'llano_grande', 'Llano Grande → Amatlán', 'Por definir', 'Comida', 0),
  ('p31', 2, 'llano_grande', 'Llano Grande → Amatlán', 'Por definir', 'Cena', 0),
  ('p31', 3, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p31', 3, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Box lunch', 0),
  ('p31', 3, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Comida', 0),
  ('p31', 3, 'lachatao', 'Lachatao → Latuvi', 'Por definir', 'Cena', 0),
  ('p31', 4, 'latuvi', 'Latuvi → Cuajimoloyas', 'Por definir', 'Desayuno', 0),
  ('p31', 4, 'latuvi', 'Latuvi → Cuajimoloyas', 'Comedor Martha', 'Comida', 0),
  ('p31', 4, 'latuvi', 'Latuvi → Cuajimoloyas', 'Comedor el Mirador', 'Cena', 0),
  ('p31', 5, 'cuajimoloyas', 'Cuajimoloyas', 'Comedor el Mirador', 'Desayuno', 0),
  ('p31', 5, 'cuajimoloyas', 'Cuajimoloyas', 'Comedor Marlen', 'Comida', 0),
  ('p32', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Comida', 0),
  ('p32', 1, 'llano_grande', 'Llano Grande', 'Por definir', 'Cena', 0),
  ('p32', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Por definir', 'Desayuno', 0),
  ('p32', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Restaurante Marlen', 'Comida', 0),
  ('p32', 2, 'llano_grande', 'Llano Grande → Cuajimoloyas', 'Restaurante Mirador', 'Cena', 0),
  ('p32', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Por definir', 'Desayuno', 0),
  ('p32', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Granja del Señor Elí', 'Comida', 0),
  ('p32', 3, 'cuajimoloyas', 'Cuajimoloyas → Benito Juárez', 'Comedor del pueblo', 'Cena', 0),
  ('p32', 4, 'benito_juarez', 'Benito Juárez → La Nevería', 'comedor del pueblo', 'Desayuno', 0),
  ('p32', 4, 'benito_juarez', 'Benito Juárez → La Nevería', 'Por definir', 'Comida', 0),
  ('p32', 5, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Desayuno', 0),
  ('p32', 5, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Comida', 0),
  ('p32', 5, 'la_neveria', 'La Nevería → Latuvi', 'Por definir', 'Cena', 0),
  ('p32', 6, 'latuvi', 'Latuvi → Lachatao', 'Por definir', 'Desayuno', 0),
  ('p32', 6, 'latuvi', 'Latuvi → Lachatao', 'Por definir', 'Box lunch', 0),
  ('p32', 6, 'latuvi', 'Latuvi → Lachatao', 'en Lachatao', 'Comida', 0),
  ('p32', 6, 'latuvi', 'Latuvi → Lachatao', 'en Amatlán', 'Cena', 0),
  ('p32', 7, 'amatlan', 'Amatlán', 'Por definir', 'Desayuno', 0),
  ('p32', 7, 'amatlan', 'Amatlán', '/Trucha el Rescate', 'Comida', 0);

-- SERVICIOS INDIVIDUALES
insert into servicios (nombre, unidad, comunidad_id, precio) values
  ('Anfitrión bilingüe (ES/EN)', 'por día', null, 0),
  ('Transporte Oaxaca – Sierra (van)', 'por viaje', null, 0),
  ('Transporte entre comunidades', 'por traslado', null, 0),
  ('Guía de sendero', 'por día', null, 0),
  ('Puente colgante', 'por persona', 'cuajimoloyas', 0),
  ('Tirolesa (línea de 3)', 'por persona', 'benito_juarez', 0),
  ('Tirolesa 1 km', 'por persona', 'cuajimoloyas', 0),
  ('Temazcal', 'por persona', 'capulalpam', 0),
  ('Hospedaje en cabaña', 'por noche', null, 0),
  ('Comedor (desayuno/comida/cena)', 'por persona', null, 0),
  ('Box lunch', 'por persona', null, 0),
  ('Taller de pan serrano', 'por persona', 'llano_grande', 0),
  ('Taller Los Colores del Maíz', 'por persona', 'la_neveria', 0),
  ('Taller de hongos', 'por persona', 'cuajimoloyas', 0),
  ('Taller de Pulque y Tepache', 'por persona', 'latuvi', 0),
  ('Plantas medicinales con degustación de té', 'por persona', 'cuajimoloyas', 0),
  ('Observación de aves', 'por persona', 'benito_juarez', 0),
  ('Acceso al museo de Amatlán', 'por persona', 'amatlan', 0);

